---
- name: Install dependencies for Nethermind
  ansible.builtin.package:
    name:
      - libsnappy-dev
      - libc6-dev
      - libc6
      - unzip
    state: latest
  become: true
  when: ansible_os_family != "Darwin"

- name: Include version setter task
  ansible.builtin.include_tasks: "version.yml"
  when: nethermind_build_from_source is false

- name: Ensure nethermind group exists
  group:
    name: "{{ nethermind_group }}"
    state: present
  become: true

- name: Create nethermind user
  user:
    comment: nethermind client user
    name: "{{ nethermind_user }}"
    group: "{{ nethermind_group }}"
  become: true

- name: Create base directory
  file:
    path: "{{ nethermind_base_dir }}"
    state: directory
    owner: "{{ nethermind_user }}"
    group: "{{ nethermind_group }}"
  become: true

- name: Create install directory
  file:
    path: "{{ nethermind_install_dir }}"
    state: directory
    owner: "{{ nethermind_user }}"
    group: "{{ nethermind_group }}"
  become: true

- name: Create log directory
  file:
    path: "{{ nethermind_log_dir }}"
    state: directory
    owner: "{{ nethermind_user }}"
    group: "{{ nethermind_group }}"
  become: true

- name: Setup logrotate
  template:
    src: "logrotate/nethermind"
    dest: "/etc/logrotate.d/nethermind"
  become: true

- name: Extract nethermind binary to install directory
  unarchive:
    src: "{{ nethermind_download_url }}"
    remote_src: "{{ true }}"
    dest: "{{ nethermind_install_dir }}"
    owner: "{{ nethermind_user }}"
    group: "{{ nethermind_group }}"
    mode: "0775"
  become: true
  register: extract_src

- name: Set updated optionally to trigger a systemd restart at the end
  set_fact:
    nethermind_state_updates: "{{ nethermind_state_updates + ['nethermind.install_dir'] }}"
  when: extract_src is changed

# will throw error the first time you install since the service isnt present
- name: Stop nethermind systemd service if running
  service:
    name: nethermind
    state: stopped
  when: ( extract_src is changed ) and
    ( nethermind_managed_service ) and
    ( ansible_os_family != "Darwin" )
  become: true
  ignore_errors: true

- name: Create a symlink to current
  file:
    src: "{{ nethermind_install_dir }}/"
    dest: "{{ nethermind_current_dir }}"
    state: link
  become: true
