---
- name: Create nethermind systemd service
  template:
    src: "{{ nethermind_systemd_template }}"
    dest: "{{ nethermind_systemd_dir }}/nethermind.service"
    owner: "root"
    group: "root"
  become: true
  when: ( nethermind_managed_service ) and
    ( ansible_os_family != "Darwin" )
  register: systemd_file

- name: Set updated optionally to trigger a systemd restart at the end
  set_fact:
    nethermind_state_updates: "{{ nethermind_state_updates + ['nethermind.systemd_file'] }}"
  when: systemd_file is changed

- name: Reload systemd to reread configs
  systemd:
    daemon_reload: yes
  become: true
  when: systemd_file is changed

- name: Enable and start nethermind service
  systemd:
    name: nethermind
    state: "{{ nethermind_systemd_state }}"
    enabled: true
  become: true
  when: ( nethermind_state_updates|length > 0 ) and
    ( nethermind_managed_service ) and
    ( ansible_os_family != "Darwin" )

# Darwin only
- name: Create Launchd service plist for Darwin
  template:
    src: "{{ nethermind_launchd_template }}"
    dest: "{{ nethermind_launchd_dir }}/nethermind.plist"
  become: true
  when: ( ansible_os_family == "Darwin" ) and
    ( nethermind_managed_service )
